local full_board = {
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"a",
	"b",
	"c",
	"d",
	"e",
	"f",
	"g",
	"h",
	"i",
	"j",
	"k",
	"l",
	"m",
	"n",
	"o",
	"p",
	"q",
	"r",
	"s",
	"t",
	"u",
	"v",
	"w",
	"x",
	"y",
	"z",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"0",
	"return",
	"escape",
	"backspace",
	"tab",
	"space",
	"-",
	"=",
	"[",
	"]",
	"\\",
	"#",
	";",
	"'",
	"`",
	",",
	".",
	"/",
	"capslock",
	"f1",
	"f2",
	"f3",
	"f4",
	"f5",
	"f6",
	"f7",
	"f8",
	"f9",
	"f10",
	"f11",
	"f12",
	"printscreen",
	"scrolllock",
	"pause",
	"insert",
	"home",
	"pageup",
	"delete",
	"end",
	"pagedown",
	"right",
	"left",
	"down",
	"up",
	"numlock",
	"keypad_/",
	"keypad_*",
	"keypad_-",
	"keypad_+",
	"keypad_enter",
	"keypad_1",
	"keypad_2",
	"keypad_3",
	"keypad_4",
	"keypad_5",
	"keypad_6",
	"keypad_7",
	"keypad_8",
	"keypad_9",
	"keypad_0",
	"keypad_.",
	"[NONE]", --"NONUSBACKSLASH",
	"[NONE]", --"APPLICATION",
	"[NONE]", --"POWER",
	"[NONE]", --"KP_EQUALS",
	"[NONE]", --"F13",
	"[NONE]", --"F14",
	"[NONE]", --"F15",
	"[NONE]", --"F16",
	"[NONE]", --"F17",
	"[NONE]", --"F18",
	"[NONE]", --"F19",
	"[NONE]", --"F20",
	"[NONE]", --"F21",
	"[NONE]", --"F22",
	"[NONE]", --"F23",
	"[NONE]", --"F24",
	"[NONE]", --"EXECUTE",
	"[NONE]", --"HELP",
	"[NONE]", --"MENU",
	"[NONE]", --"SELECT",
	"[NONE]", --"STOP",
	"[NONE]", --"AGAIN",
	"[NONE]", --"UNDO",
	"[NONE]", --"CUT",
	"[NONE]", --"COPY",
	"[NONE]", --"PASTE",
	"[NONE]", --"FIND",
	"[NONE]", --"MUTE",
	"[NONE]", --"VOLUMEUP",
	"[NONE]", --"VOLUMEDOWN",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"keypad_,",
	"[NONE]", --"KP_EQUALSAS400",
	"[NONE]", --"INTERNATIONAL1",
	"[NONE]", --"INTERNATIONAL2",
	"[NONE]", --"INTERNATIONAL3",
	"[NONE]", --"INTERNATIONAL4",
	"[NONE]", --"INTERNATIONAL5",
	"[NONE]", --"INTERNATIONAL6",
	"[NONE]", --"INTERNATIONAL7",
	"[NONE]", --"INTERNATIONAL8",
	"[NONE]", --"INTERNATIONAL9",
	"[NONE]", --"LANG1",
	"[NONE]", --"LANG2",
	"[NONE]", --"LANG3",
	"[NONE]", --"LANG4",
	"[NONE]", --"LANG5",
	"[NONE]", --"LANG6",
	"[NONE]", --"LANG7",
	"[NONE]", --"LANG8",
	"[NONE]", --"LANG9",
	"[NONE]", --"ALTERASE",
	"[NONE]", --"SYSREQ",
	"[NONE]", --"CANCEL",
	"[NONE]", --"CLEAR",
	"[NONE]", --"PRIOR",
	"[NONE]", --"RETURN2",
	"[NONE]", --"SEPARATOR",
	"[NONE]", --"OUT",
	"[NONE]", --"OPER",
	"[NONE]", --"CLEARAGAIN",
	"[NONE]", --"CRSEL",
	"[NONE]", --"EXSEL",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]", --"KP_00",
	"[NONE]", --"KP_000",
	"[NONE]", --"THOUSANDSSEPARATOR",
	"[NONE]", --"DECIMALSEPARATOR",
	"[NONE]", --"CURRENCYUNIT",
	"[NONE]", --"CURRENCYSUBUNIT",
	"[NONE]", --"KP_LEFTPAREN",
	"[NONE]", --"KP_RIGHTPAREN",
	"[NONE]", --"KP_LEFTBRACE",
	"[NONE]", --"KP_RIGHTBRACE",
	"[NONE]", --"KP_TAB",
	"[NONE]", --"KP_BACKSPACE",
	"[NONE]", --"KP_A",
	"[NONE]", --"KP_B",
	"[NONE]", --"KP_C",
	"[NONE]", --"KP_D",
	"[NONE]", --"KP_E",
	"[NONE]", --"KP_F",
	"[NONE]", --"KP_XOR",
	"[NONE]", --"KP_POWER",
	"[NONE]", --"KP_PERCENT",
	"[NONE]", --"KP_LESS",
	"[NONE]", --"KP_GREATER",
	"[NONE]", --"KP_AMPERSAND",
	"[NONE]", --"KP_DBLAMPERSAND",
	"[NONE]", --"KP_VERTICALBAR",
	"[NONE]", --"KP_DBLVERTICALBAR",
	"[NONE]", --"KP_COLON",
	"[NONE]", --"KP_HASH",
	"[NONE]", --"KP_SPACE",
	"[NONE]", --"KP_AT",
	"[NONE]", --"KP_EXCLAM",
	"[NONE]", --"KP_MEMSTORE",
	"[NONE]", --"KP_MEMRECALL",
	"[NONE]", --"KP_MEMCLEAR",
	"[NONE]", --"KP_MEMADD",
	"[NONE]", --"KP_MEMSUBTRACT",
	"[NONE]", --"KP_MEMMULTIPLY",
	"[NONE]", --"KP_MEMDIVIDE",
	"[NONE]", --"KP_PLUSMINUS",
	"[NONE]", --"KP_CLEAR",
	"[NONE]", --"KP_CLEARENTRY",
	"[NONE]", --"KP_BINARY",
	"[NONE]", --"KP_OCTAL",
	"[NONE]", --"KP_DECIMAL",
	"[NONE]", --"KP_HEXADECIMAL",
	"[NONE]",
	"[NONE]",
	"left_ctrl",
	"left_shift",
	"left_alt",
	"left_windows",
	"right_ctrl",
	"right_shift",
	"right_alt",
	"right_windows",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "MODE",
	-- "AUDIONEXT",
	-- "AUDIOPREV",
	-- "AUDIOSTOP",
	-- "AUDIOPLAY",
	-- "AUDIOMUTE",
	-- "MEDIASELECT",
	-- "WWW",
	-- "MAIL",
	-- "CALCULATOR",
	-- "COMPUTER",
	-- "AC_SEARCH",
	-- "AC_HOME",
	-- "AC_BACK",
	-- "AC_FORWARD",
	-- "AC_STOP",
	-- "AC_REFRESH",
	-- "AC_BOOKMARKS",
	-- "BRIGHTNESSDOWN",
	-- "BRIGHTNESSUP",
	-- "DISPLAYSWITCH",
	-- "KBDILLUMTOGGLE",
	-- "KBDILLUMDOWN",
	-- "KBDILLUMUP",
	-- "EJECT",
	-- "SLEEP",
	-- "APP1",
	-- "APP2",
}

local full_mouse = {
	"mouse_left",
	"mouse_right",
	"mouse_middle",
	"mouse_wheel_up",
	"mouse_wheel_down",
	"mouse_extra_1",
	"mouse_extra_2",
}

return { full_board, full_mouse }