--[[gamepad button list
[*] states the gamepad number; non-standard gamepads might be supported but extra buttons will not be listed here - check naming during rebinding

[*]gpd_y
[*]gpd_x
[*]gpd_a
[*]gpd_b

[*]gpd_r1
[*]gpd_r2
[*]gpd_r3
[*]gpd_l1
[*]gpd_l2
[*]gpd_l3

[*]gpd_up
[*]gpd_down
[*]gpd_left
[*]gpd_right

[*]gpd_select
[*]gpd_start

[*]gpd_btn_lh_+
[*]gpd_btn_lh_-
[*]gpd_btn_lv_+
[*]gpd_btn_lv_-
[*]gpd_btn_rh_+
[*]gpd_btn_rh_-
[*]gpd_btn_rv_+
[*]gpd_btn_rv_-

]]

--[[gamepad analog axis list
[*] states the gamepad number; non-standard gamepads might be supported but extra buttons will not be listed here - check naming after rebinding

[*]gpd_axis_lh
[*]gpd_axis_lv
[*]gpd_axis_rh
[*]gpd_axis_rv

bindings["jpad_example"] = {
	stuff_1 = {
		name = "Check This Out",
		desc = "You can have either proper analog input or a pair of buttons. This one is generic.",
		keys = { "is_axis", "1gpd_axis_lh", },
	},
	stuff_2 = {
		name = "Behold the Ultimate Power of Complete Input",
		desc = "And this one is extra buttoned.",
		keys = { "is_axis", "keypad_+", "keypad_-", },
	},
	stuff_real = {
		name = "Stick Moment",
		desc = "Enables one to have a properly deadzoned and overall convenient stick binding.",
		is_raw = false, --[DISABLES JOYSTICK NORMALIZATION]
		axes = { "stuff_1", "stuff_2", },
	}
}

]]

local full_board = {
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"a",
	"b",
	"c",
	"d",
	"e",
	"f",
	"g",
	"h",
	"i",
	"j",
	"k",
	"l",
	"m",
	"n",
	"o",
	"p",
	"q",
	"r",
	"s",
	"t",
	"u",
	"v",
	"w",
	"x",
	"y",
	"z",
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9",
	"0",
	"return",
	"escape",
	"backspace",
	"tab",
	"space",
	"-",
	"=",
	"[",
	"]",
	"\\",
	"#",
	";",
	"'",
	"`",
	",",
	".",
	"/",
	"capslock",
	"f1",
	"f2",
	"f3",
	"f4",
	"f5",
	"f6",
	"f7",
	"f8",
	"f9",
	"f10",
	"f11",
	"f12",
	"printscreen",
	"scrolllock",
	"pause",
	"insert",
	"home",
	"pageup",
	"delete",
	"end",
	"pagedown",
	"right",
	"left",
	"down",
	"up",
	"numlock",
	"keypad_/",
	"keypad_*",
	"keypad_-",
	"keypad_+",
	"keypad_enter",
	"keypad_1",
	"keypad_2",
	"keypad_3",
	"keypad_4",
	"keypad_5",
	"keypad_6",
	"keypad_7",
	"keypad_8",
	"keypad_9",
	"keypad_0",
	"keypad_.",
	"[NONE]", --"NONUSBACKSLASH",
	"[NONE]", --"APPLICATION",
	"[NONE]", --"POWER",
	"[NONE]", --"KP_EQUALS",
	"[NONE]", --"F13",
	"[NONE]", --"F14",
	"[NONE]", --"F15",
	"[NONE]", --"F16",
	"[NONE]", --"F17",
	"[NONE]", --"F18",
	"[NONE]", --"F19",
	"[NONE]", --"F20",
	"[NONE]", --"F21",
	"[NONE]", --"F22",
	"[NONE]", --"F23",
	"[NONE]", --"F24",
	"[NONE]", --"EXECUTE",
	"[NONE]", --"HELP",
	"[NONE]", --"MENU",
	"[NONE]", --"SELECT",
	"[NONE]", --"STOP",
	"[NONE]", --"AGAIN",
	"[NONE]", --"UNDO",
	"[NONE]", --"CUT",
	"[NONE]", --"COPY",
	"[NONE]", --"PASTE",
	"[NONE]", --"FIND",
	"[NONE]", --"MUTE",
	"[NONE]", --"VOLUMEUP",
	"[NONE]", --"VOLUMEDOWN",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"keypad_,",
	"[NONE]", --"KP_EQUALSAS400",
	"[NONE]", --"INTERNATIONAL1",
	"[NONE]", --"INTERNATIONAL2",
	"[NONE]", --"INTERNATIONAL3",
	"[NONE]", --"INTERNATIONAL4",
	"[NONE]", --"INTERNATIONAL5",
	"[NONE]", --"INTERNATIONAL6",
	"[NONE]", --"INTERNATIONAL7",
	"[NONE]", --"INTERNATIONAL8",
	"[NONE]", --"INTERNATIONAL9",
	"[NONE]", --"LANG1",
	"[NONE]", --"LANG2",
	"[NONE]", --"LANG3",
	"[NONE]", --"LANG4",
	"[NONE]", --"LANG5",
	"[NONE]", --"LANG6",
	"[NONE]", --"LANG7",
	"[NONE]", --"LANG8",
	"[NONE]", --"LANG9",
	"[NONE]", --"ALTERASE",
	"[NONE]", --"SYSREQ",
	"[NONE]", --"CANCEL",
	"[NONE]", --"CLEAR",
	"[NONE]", --"PRIOR",
	"[NONE]", --"RETURN2",
	"[NONE]", --"SEPARATOR",
	"[NONE]", --"OUT",
	"[NONE]", --"OPER",
	"[NONE]", --"CLEARAGAIN",
	"[NONE]", --"CRSEL",
	"[NONE]", --"EXSEL",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]",
	"[NONE]", --"KP_00",
	"[NONE]", --"KP_000",
	"[NONE]", --"THOUSANDSSEPARATOR",
	"[NONE]", --"DECIMALSEPARATOR",
	"[NONE]", --"CURRENCYUNIT",
	"[NONE]", --"CURRENCYSUBUNIT",
	"[NONE]", --"KP_LEFTPAREN",
	"[NONE]", --"KP_RIGHTPAREN",
	"[NONE]", --"KP_LEFTBRACE",
	"[NONE]", --"KP_RIGHTBRACE",
	"[NONE]", --"KP_TAB",
	"[NONE]", --"KP_BACKSPACE",
	"[NONE]", --"KP_A",
	"[NONE]", --"KP_B",
	"[NONE]", --"KP_C",
	"[NONE]", --"KP_D",
	"[NONE]", --"KP_E",
	"[NONE]", --"KP_F",
	"[NONE]", --"KP_XOR",
	"[NONE]", --"KP_POWER",
	"[NONE]", --"KP_PERCENT",
	"[NONE]", --"KP_LESS",
	"[NONE]", --"KP_GREATER",
	"[NONE]", --"KP_AMPERSAND",
	"[NONE]", --"KP_DBLAMPERSAND",
	"[NONE]", --"KP_VERTICALBAR",
	"[NONE]", --"KP_DBLVERTICALBAR",
	"[NONE]", --"KP_COLON",
	"[NONE]", --"KP_HASH",
	"[NONE]", --"KP_SPACE",
	"[NONE]", --"KP_AT",
	"[NONE]", --"KP_EXCLAM",
	"[NONE]", --"KP_MEMSTORE",
	"[NONE]", --"KP_MEMRECALL",
	"[NONE]", --"KP_MEMCLEAR",
	"[NONE]", --"KP_MEMADD",
	"[NONE]", --"KP_MEMSUBTRACT",
	"[NONE]", --"KP_MEMMULTIPLY",
	"[NONE]", --"KP_MEMDIVIDE",
	"[NONE]", --"KP_PLUSMINUS",
	"[NONE]", --"KP_CLEAR",
	"[NONE]", --"KP_CLEARENTRY",
	"[NONE]", --"KP_BINARY",
	"[NONE]", --"KP_OCTAL",
	"[NONE]", --"KP_DECIMAL",
	"[NONE]", --"KP_HEXADECIMAL",
	"[NONE]",
	"[NONE]",
	"left_ctrl",
	"left_shift",
	"left_alt",
	"left_windows",
	"right_ctrl",
	"right_shift",
	"right_alt",
	"right_windows",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "[NONE]",
	-- "MODE",
	-- "AUDIONEXT",
	-- "AUDIOPREV",
	-- "AUDIOSTOP",
	-- "AUDIOPLAY",
	-- "AUDIOMUTE",
	-- "MEDIASELECT",
	-- "WWW",
	-- "MAIL",
	-- "CALCULATOR",
	-- "COMPUTER",
	-- "AC_SEARCH",
	-- "AC_HOME",
	-- "AC_BACK",
	-- "AC_FORWARD",
	-- "AC_STOP",
	-- "AC_REFRESH",
	-- "AC_BOOKMARKS",
	-- "BRIGHTNESSDOWN",
	-- "BRIGHTNESSUP",
	-- "DISPLAYSWITCH",
	-- "KBDILLUMTOGGLE",
	-- "KBDILLUMDOWN",
	-- "KBDILLUMUP",
	-- "EJECT",
	-- "SLEEP",
	-- "APP1",
	-- "APP2",
}

local full_mouse = {
	"mouse_left",
	"mouse_right",
	"mouse_middle",
	"mouse_wheel_up",
	"mouse_wheel_down",
	"mouse_extra_1",
	"mouse_extra_2",
}

local full_joy = {
	"analog_0",
	"analog_1",
	"analog_2",
	"analog_3",
	"analog_4",
	"analog_5",
	"analog_6",
	"analog_7",
	"analog_8",
	"analog_9",
	"up",
	"down",
	"left",
	"right",
	"start",
	"select",
	"l3",
	"r3",
	"l1",
	"r1",
	"[NONE]", --l2
	"[NONE]", --r2
	"a",
	"b",
	"x",
	"y",
	"btn_4",
	"btn_5",
	"btn_6",
	"btn_7",
	"btn_8",
	"btn_9",
	"btn_10",
	"btn_11",
	"btn_12",
	"btn_13",
	"btn_14",
	"btn_15",
	"[NONE]", --"btn_lh_+",
	"[NONE]", --"btn_lh_-",
	"[NONE]", --"btn_lv_+",
	"[NONE]", --"btn_lv_-",
	"[NONE]", --"btn_rh_+",
	"[NONE]", --"btn_rh_-",
	"[NONE]", --"btn_rv_+",
	"[NONE]", --"btn_rv_-",
	"[NONE]", --"analog_0_down", this conflicts with l2
	"[NONE]", --"analog_1_down", this conflicts with r2
	"analog_2_down",
	"analog_3_down",
	"analog_4_down",
	"analog_5_down",
	"analog_6_down",
	"analog_7_down",
	"analog_8_down",
	"analog_9_down",
}

local full_shifted = {
	["1"] = "!",
	["2"] = "@",
	["3"] = "#",
	["4"] = "$",
	["5"] = "%",
	["6"] = "^",
	["7"] = "&",
	["8"] = "*",
	["9"] = "(",
	["0"] = ")",
	["space"] = " ",
	["backspace"] = -2,
	["return"] = -3,
	["tab"] = -4,
	["-"] = "_",
	["="] = "+",
	["["] = "{",
	["]"] = "}",
	["\\"] = "|",
	["#"] = "№",
	[";"] = ":",
	["'"] = "\"",
	["`"] = "~",
	[","] = "<",
	["."] = ">",
	["/"] = "?",
}

local full_fancy = {
	["a"] = "A",
	["b"] = "B",
	["c"] = "C",
	["d"] = "D",
	["e"] = "E",
	["f"] = "F",
	["g"] = "G",
	["h"] = "H",
	["i"] = "I",
	["j"] = "J",
	["k"] = "K",
	["l"] = "L",
	["m"] = "M",
	["n"] = "N",
	["o"] = "O",
	["p"] = "P",
	["q"] = "Q",
	["r"] = "R",
	["s"] = "S",
	["t"] = "T",
	["u"] = "U",
	["v"] = "V",
	["w"] = "W",
	["x"] = "X",
	["y"] = "Y",
	["z"] = "Z",
	
	-- "1",
	-- "2",
	-- "3",
	-- "4",
	-- "5",
	-- "6",
	-- "7",
	-- "8",
	-- "9",
	-- "0",
	
	["-"] = {[2]="Minus"},
	["="] = {[2]="Equals"},
	["["] = {[2]="Left Bracket"},
	["]"] = {[2]="Right Bracket"},
	["\\"] = {[2]="Backslash"},
	["#"] = {[2]="Hash"},
	[";"] = {[2]="Semicolon"},
	["'"] = {[2]="Apostrophe"},
	["`"] = {[2]="Grave"},
	[","] = {[2]="Comma"},
	["."] = {[2]="Period"},
	["/"] = {[2]="Slash"},

	["keypad_/"] = {"KPd(/)","Keypad Slash"},
	["keypad_*"] = {"KPd(*)","Keypad Asterisk"},
	["keypad_-"] = {"KPd(-)","Keypad Minus"},
	["keypad_+"] = {"KPd(+)","Keypad Plus"},
	["keypad_enter"] = {"KPd(rtrn)","Keypad Return"},
	["keypad_1"] = {"KPd(1)","Keypad 1"},
	["keypad_2"] = {"KPd(2)","Keypad 2"},
	["keypad_3"] = {"KPd(3)","Keypad 3"},
	["keypad_4"] = {"KPd(4)","Keypad 4"},
	["keypad_5"] = {"KPd(5)","Keypad 5"},
	["keypad_6"] = {"KPd(6)","Keypad 6"},
	["keypad_7"] = {"KPd(7)","Keypad 7"},
	["keypad_8"] = {"KPd(8)","Keypad 8"},
	["keypad_9"] = {"KPd(9)","Keypad 9"},
	["keypad_0"] = {"KPd(0)","Keypad 0"},
	["keypad_."] = {"KPd(.)","Keypad Dot"},
	["keypad_,"] = {"KPd(,)","Keypad Comma"},

	["left_ctrl"] = {"LCtrl","Left Control"},
	["left_shift"] = {"LShift","Left Shift"},
	["left_alt"] = {"LAlt","Left Alt"},
	["left_windows"] = {"LWin","Left Windows Key"},
	["right_ctrl"] = {"RCtrl","Right Control"},
	["right_shift"] = {"RShift","Right Shift"},
	["right_alt"] = {"RAlt","Right Alt"},
	["right_windows"] = {"RWin","Right Windows Key"},

	["return"] = "Enter",
	["escape"] = {"Esc","Escape"},
	["backspace"] = "Backspace",
	["tab"] = "Tab",
	["space"] = "Space",
	["delete"] = "Delete",
	["pause"] = "Pause",
	["insert"] = "Insert",
	
	["right"] = "Right",
	["left"] = "Left",
	["down"] = "Down",
	["up"] = "Up",
	
	["home"] = "Home",
	["end"] = "End",
	["pageup"] = "PageUp",
	["pagedown"] = "PageDown",

	["f1"] = "F1",
	["f2"] = "F2",
	["f3"] = "F3",
	["f4"] = "F4",
	["f5"] = "F5",
	["f6"] = "F6",
	["f7"] = "F7",
	["f8"] = "F8",
	["f9"] = "F9",
	["f10"] = "F10",
	["f11"] = "F11",
	["f12"] = "F12",

	["printscreen"] = {"PrtSc","PrintScreen"},
	["scrolllock"] = {"ScrLk","ScrollLock"},
	["numlock"] = {"NumLk","NumLock"},
	["capslock"] = {"CpsLk","CapsLock"},

	["analog_0"] = {"a0+","RawAnalog0"},
	["analog_1"] = {"a1+","RawAnalog1"},
	["analog_2"] = {"a2+","RawAnalog2"},
	["analog_3"] = {"a3+","RawAnalog3"},
	["analog_4"] = {"a4+","RawAnalog4"},
	["analog_5"] = {"a5+","RawAnalog5"},
	["analog_6"] = {"a6+","RawAnalog6"},
	["analog_7"] = {"a7+","RawAnalog7"},
	["analog_8"] = {"a8+","RawAnalog8"},
	["analog_9"] = {"a9+","RawAnalog9"},

	["start"] = "Start",
	["select"] = "Select",

	["l3"] = {"LThmb","Left Thumb (L3)"},
	["r3"] = {"RThmb","Right Thumb (R3)"},
	["l1"] = {"LBump","Left Bumper (L1)"},
	["r1"] = {"RBump","Right Bumper (R1)"},
	["l2"] = {"LTrgr","Left Trigger (L2)"},
	["r2"] = {"RTrgr","Right Trigger (R2)"},

	["btn_a"] = {"A","A (Cross)"},
	["btn_b"] = {"B","B (Circle)"},
	["btn_x"] = {"X","X (Square)"},
	["btn_y"] = {"Y","Y (Triangle)"},
	["btn_4"] = {"4","Gamepad4"},
	["btn_5"] = {"5","Gamepad5"},
	["btn_6"] = {"6","Gamepad6"},
	["btn_7"] = {"7","Gamepad7"},
	["btn_8"] = {"8","Gamepad8"},
	["btn_9"] = {"9","Gamepad9"},
	["btn_10"] = {"10","Gamepad10"},
	["btn_11"] = {"11","Gamepad11"},
	["btn_12"] = {"12","Gamepad12"},
	["btn_13"] = {"13","Gamepad13"},
	["btn_14"] = {"14","Gamepad14"},
	["btn_15"] = {"15","Gamepad15"},
	
	["analog_0_down"] = {"a0","Analog0"},
	["analog_1_down"] = {"a1","Analog1"},
	["analog_2_down"] = {"a2","Analog2"},
	["analog_3_down"] = {"a3","Analog3"},
	["analog_4_down"] = {"a4","Analog4"},
	["analog_5_down"] = {"a5","Analog5"},
	["analog_6_down"] = {"a6","Analog6"},
	["analog_7_down"] = {"a7","Analog7"},
	["analog_8_down"] = {"a8","Analog8"},
	["analog_9_down"] = {"a9","Analog9"},

	["axis_lh"] = {"LStckH","Left Stick X-Axis"},
	["axis_lv"] = {"LStckV","Left Stick Y-Axis"},
	["axis_rh"] = {"RStckH","Right Stick X-Axis"},
	["axis_rv"] = {"RStckV","Right Stick Y-Axis"},

	["btn_lh_+"] = {"LStckX+","Left Stick X-Axis+"},
	["btn_lh_-"] = {"LStckX-","Left Stick X-Axis-"},
	["btn_lv_+"] = {"LStckY+","Left Stick Y-Axis+"},
	["btn_lv_-"] = {"LStckY-","Left Stick Y-Axis-"},
	["btn_rh_+"] = {"RStckX+","Right Stick X-Axis+"},
	["btn_rh_-"] = {"RStckX-","Right Stick X-Axis-"},
	["btn_rv_+"] = {"RStckY+","Right Stick Y-Axis+"},
	["btn_rv_-"] = {"RStckY-","Right Stick Y-Axis-"},
}

local full_twin = {
	special = {
		["left_alt"] = "right_alt",
		["right_alt"] = "left_alt",
		["left_ctrl"] = "right_ctrl",
		["right_ctrl"] = "left_ctrl",
		["left_shift"] = "right_shift",
		["right_shift"] = "left_shift",
		["left_windows"] = "right_windows",
		["right_windows"] = "left_windows",
	},
	
	numpad = {
		["1"] = "keypad_1",
		["keypad_1"] = "1",
		["2"] = "keypad_2",
		["keypad_2"] = "2",
		["3"] = "keypad_3",
		["keypad_3"] = "3",
		["4"] = "keypad_4",
		["keypad_4"] = "4",
		["5"] = "keypad_5",
		["keypad_5"] = "5",
		["6"] = "keypad_6",
		["keypad_6"] = "6",
		["7"] = "keypad_7",
		["keypad_7"] = "7",
		["8"] = "keypad_8",
		["keypad_8"] = "8",
		["9"] = "keypad_9",
		["keypad_9"] = "9",
		["0"] = "keypad_0",
		["keypad_0"] = "0",

		["return"] = "keypad_enter",
		["keypad_enter"] = "return",
		["-"] = "keypad_-",
		["keypad_-"] = "-",
		[","] = "keypad_,",
		["keypad_,"] = ",",
		["."] = "keypad_.",
		["keypad_."] = ".",
		["/"] = "keypad_/",
		["keypad_/"] = "/",
	},
}

local full_keys = {
	{
		[""] = {
			name = "Latin", off = 158,
			path = "mods/mnee/files/pics/keyboard/",
		},

		["`"] = { "`", "~",    "©", "∞" },
		["/"] = { "/", "?",    "â", "Â" },
		["1"] = { "1", "!",    "ã", "Ã" },
		["2"] = { "2", "ⓐ",    "ą", "Ą" },
		["3"] = { "3", "#",    "ć", "Ć" },
		["4"] = { "4", "$",    "ê", "Ê" },
		["5"] = { "5", "%",    "ę", "Ę" },
		["6"] = { "6", "^",    "î", "Î" },
		["7"] = { "7", "&",    "ń", "Ń" },
		["8"] = { "8", "*",    "ś", "Ś" },
		["9"] = { "9", "(",    "ź", "Ź" },
		["0"] = { "0", ")",    "ż", "Ż" },
		["-"] = { "-", "_",    "«", "»" },
		["="] = { "=", "+",    "—", "¬" },
		
		["\\"] = { "\\", "|",    "¡", "¿" },
		["q"] = { "q", "Q",    "æ", "Æ" },
		["w"] = { "w", "W",    "å", "Å" },
		["e"] = { "e", "E",    "ë", "Ë" },
		["r"] = { "r", "R",    "ý", "Ý" },
		["t"] = { "t", "T",    "þ", "Þ" },
		["y"] = { "y", "Y",    "ÿ", "Ÿ" },
		["u"] = { "u", "U",    "ü", "Ü" },
		["i"] = { "i", "I",    "ï", "Ï" },
		["o"] = { "o", "O",    "ö", "Ö" },
		["p"] = { "p", "P",    "œ", "Œ" },
		["\'"] = { "\'", "\"",    "û", "Û" },

		["a"] = { "a", "A",    "ä", "Ä" },
		["s"] = { "s", "S",    "ß", "ẞ" },
		["d"] = { "d", "D",    "đ", "Đ" },
		["f"] = { "f", "F",    "è", "È" },
		["g"] = { "g", "G",    "é", "É" },
		["h"] = { "h", "H",    "ù", "Ù" },
		["j"] = { "j", "J",    "ú", "Ú" },
		["k"] = { "k", "K",    "ĳ", "Ĳ" },
		["l"] = { "l", "L",    "ø", "Ø" },
		["["] = { "[", "{",    "ô", "Ô" },
		["]"] = { "]", "}",    "ł", "Ł" },

		["z"] = { "z", "Z",    "à", "À" },
		["x"] = { "x", "X",    "á", "Á" },
		["c"] = { "c", "C",    "ç", "Ç" },
		["v"] = { "v", "V",    "ì", "Ì" },
		["b"] = { "b", "B",    "í", "Í" },
		["n"] = { "n", "N",    "ñ", "Ñ" },
		["m"] = { "m", "M",    "õ", "Õ" },
		[","] = { ",", "<",    "ò", "Ò" },
		["."] = { ".", ">",    "ó", "Ó" },
		[";"] = { ";", ":",    "°", "…" },
	},

	{
		[""] = {
			name = "Русский", off = 316,
			path = "mods/mnee/files/pics/keyboard/",
		},

		["`"] = { "ё", "Ё" },
		["/"] = { "\\", "/" },
		["1"] = { "1", "!" },
		["2"] = { "2", "\"" },
		["3"] = { "3", "#" },
		["4"] = { "4", ";" },
		["5"] = { "5", "%" },
		["6"] = { "6", ":" },
		["7"] = { "7", "?" },
		["8"] = { "8", "*" },
		["9"] = { "9", "(" },
		["0"] = { "0", ")" },
		["-"] = { "-", "_" },
		["="] = { "=", "+" },
		
		["\\"] = { "й", "Й" },
		["q"] = { "ц", "Ц" },
		["w"] = { "у", "У" },
		["e"] = { "к", "К" },
		["r"] = { "е", "Е" },
		["t"] = { "н", "Н" },
		["y"] = { "г", "Г" },
		["u"] = { "ш", "Ш" },
		["i"] = { "щ", "Щ" },
		["o"] = { "з", "З" },
		["p"] = { "х", "Х" },
		["\'"] = { "ъ", "Ъ" },

		["a"] = { "ф", "Ф" },
		["s"] = { "ы", "Ы" },
		["d"] = { "в", "В" },
		["f"] = { "а", "А" },
		["g"] = { "п", "П" },
		["h"] = { "р", "Р" },
		["j"] = { "о", "О" },
		["k"] = { "л", "Л" },
		["l"] = { "д", "Д" },
		["["] = { "ж", "Ж" },
		["]"] = { "э", "Э" },

		["z"] = { "я", "Я" },
		["x"] = { "ч", "Ч" },
		["c"] = { "с", "С" },
		["v"] = { "м", "М" },
		["b"] = { "и", "И" },
		["n"] = { "т", "Т" },
		["m"] = { "ь", "Ь" },
		[","] = { "б", "Б" },
		["."] = { "ю", "Ю" },
		[";"] = { ".", "," },
	},

	-- korean = {
	--	[""] = {
	--		name = "", off = 0, is_hd = true,
	--		path = "mods/mnee/files/pics/keyboard/_hd.png",
	--	},

	-- 	["`"] = { "`", "~",    "", "",    "", "",    "", "" },
	-- },

	-- chinese = {},

	-- japanese = {},
}

local full_offs = {
	["`"] = { 3, 3 },
	["/"] = { 14, 3 },
	["1"] = { 25, 3 },
	["2"] = { 36, 3 },
	["3"] = { 47, 3 },
	["4"] = { 58, 3 },
	["5"] = { 69, 3 },
	["6"] = { 80, 3 },
	["7"] = { 91, 3 },
	["8"] = { 102, 3 },
	["9"] = { 113, 3 },
	["0"] = { 124, 3 },
	["-"] = { 135, 3 },
	["="] = { 146, 3 },
	
	["\\"] = { 14, 14 },
	["q"] = { 25, 14 },
	["w"] = { 36, 14 },
	["e"] = { 47, 14 },
	["r"] = { 58, 14 },
	["t"] = { 69, 14 },
	["y"] = { 80, 14 },
	["u"] = { 91, 14 },
	["i"] = { 102, 14 },
	["o"] = { 113, 14 },
	["p"] = { 124, 14 },
	["\'"] = { 135, 14 },
	
	["a"] = { 25, 25 },
	["s"] = { 36, 25 },
	["d"] = { 47, 25 },
	["f"] = { 58, 25 },
	["g"] = { 69, 25 },
	["h"] = { 80, 25 },
	["j"] = { 91, 25 },
	["k"] = { 102, 25 },
	["l"] = { 113, 25 },
	["["] = { 124, 25 },
	["]"] = { 135, 25 },
	
	["z"] = { 36, 36 },
	["x"] = { 47, 36 },
	["c"] = { 58, 36 },
	["v"] = { 69, 36 },
	["b"] = { 80, 36 },
	["n"] = { 91, 36 },
	["m"] = { 102, 36 },
	[","] = { 113, 36 },
	["."] = { 124, 36 },
	[";"] = { 135, 36 },
}

local full_nums = {
	["1"] = 1,
	["2"] = 1,
	["3"] = 1,
	["4"] = 1,
	["5"] = 1,
	["6"] = 1,
	["7"] = 1,
	["8"] = 1,
	["9"] = 1,
	["0"] = 1,
	["."] = 1,
	["e"] = 1,
	["-"] = 1,
	["*"] = 1,
	["/"] = 1,
	["+"] = 1,
	["^"] = 1,
	["%"] = 1,
	["("] = 1,
	[")"] = 1,
}

--<{> MAGICAL APPEND MARKER <}>--

return { full_board, full_mouse, full_joy, full_shifted, full_fancy, full_twin, full_keys, full_offs, full_nums }